openapi: 3.0.0
info:
  title: API Recomendation System
  description: Documentation for application recomendation system.
  version: 1.0.0

tags:
  - name: Recomendation System
  - name: School
  - name: Address
  - name: Seeder
    description: (Warning) Use the Seeder function with caution. Excessive use can negatively impact database performance (Firestore) due to increased traffic.
paths:
  # recomendation system
  /recomendation_system:
    post:
      tags:
        - Recomendation System
      summary: Return list of school basaed own user preferance
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                address:
                  type: string
                type:
                  type: string
            example:
              address: address-1
              type: sma | smk | man

      responses:
        "200":
          description: A JSON array of calculation & ranking recomendation system
        "400":
          description: body properties address is required
  # seeders
  /seeder/schools:
    get:
      tags:
        - Seeder
      summary: process seeds on firestore database table schools
      responses:
        "200":
          description: Succses & firestore database table schools updated

  /seeder/address:
    get:
      tags:
        - Seeder
      summary: process seeds on firestore database table address
      responses:
        "200":
          description: Succses & firestore database table address updated

  /seeder/distance:
    get:
      tags:
        - Seeder
      summary: process seeds on firestore database table distance
      responses:
        "200":
          description: Succses & firestore database table distance updated
